### ISSUE TITLE
troll

### ISSUE THREAD

**Issue by sylvainschmitt** [sylvainschmitt/rcontroll#3]
## Tasks

- [x] check inputs
- [x] binary path
- [x] unique label for model
- [x] system command
- [x] unlink empty/unused files
- [x] different load depending on simulation type
- [x] verbose
- [x] progress bar
- [x] document
- [x] formal testing

## Additional
