### ISSUE TITLE
load_output

### ISSUE THREAD

**Issue by sylvainschmitt** [sylvainschmitt/rcontroll#5]
## Tasks

- [x] read all outputs
- [x] consolidate files into a few attributes
- [x] internal for different classes
- [x] document
- [x] formal testing

## Additional
